### ISSUE TITLE
Testing Coverage

### ISSUE THREAD

**Issue by benxu3** [CSC207-2022F-UofT/course-project-the-best-monopoly-team#100]
We need to increase our test coverage. Afterwards, document coverage and provide clearly in the repository. 
![image](https://user-images.githubusercontent.com/57053446/206484699-094c5660-a6a4-4b1e-bad5-873d65a89a8f.png)

 
**Buttons**
- everything
![image](https://user-images.githubusercontent.com/57053446/206484276-c5c11d59-bebb-4bfc-8830-57d2545204bf.png)

**Entities**
- Description, Card, GameScreen, Options, Output, and some of Player / Property 
![image](https://user-images.githubusercontent.com/57053446/206484325-c69e7849-247b-4f59-a139-9a1cd08bec66.png)

**Interactors**
- ButtonDisplayInteractor, GameDisplayInputInteractor, GameDisplayInteractor, GameDisplayOutputInteractor, OutputInteractor, PerformActionSpaceCardInteractor, SavePackager, StateOutputReader
![image](https://user-images.githubusercontent.com/57053446/206484375-67e166e3-adfe-49ea-a8f9-6bc8d17f7f6e.png)

**Persistence**
- some of SaveFile
![image](https://user-images.githubusercontent.com/57053446/206484500-4b50f170-0902-4c99-821f-985847eeffc4.png)

**UseCases**
- PresenterDisplay, some of UseCaseInteractor
![image](https://user-images.githubusercontent.com/57053446/206484583-cdb3bcb2-b733-44a1-bf40-d072dff6f23d.png)

**Main**?

**Comment by kRichard32** [comment]
Testing coverage is pretty good now, aside from a few files, we should be good.
![image](https://user-images.githubusercontent.com/90296000/206624258-bdc20c34-9761-493c-bf6a-7f1cbe6f2351.png)
