### ISSUE TITLE
Fix text labels

### ISSUE THREAD

**Issue by kRichard32** [CSC207-2022F-UofT/course-project-the-best-monopoly-team#101]
![image](https://user-images.githubusercontent.com/90296000/206522785-3368adbe-7923-488e-8769-f418e4883389.png)
![image](https://user-images.githubusercontent.com/90296000/206522636-705da0f4-3711-421d-9923-a1d14375c1a1.png)
Might want to fix these strings in trading

**Comment by harshkpatel** [comment]
Done
