### ISSUE TITLE
[Feature 11] Use Case Interactor

### ISSUE THREAD

**Issue by harshkpatel** [CSC207-2022F-UofT/course-project-the-best-monopoly-team#11]
Implement the UseCaseInteractor and all its features. The UseCaseInteractor handles the input of the program, and decides what to do with the input and returns the appropriate menu to the presenter. Will be reviewed by Harsh, Derrick, and Susannah.

**Comment by kRichard32** [comment]
Use case interactor is too much of a vague feature to complete. Will create smaller issues that encompass this whole issue as a whole.
