### ISSUE TITLE
[Feature 12] Load/Save Functionality

### ISSUE THREAD

**Issue by harshkpatel** [CSC207-2022F-UofT/course-project-the-best-monopoly-team#12]
Implement the DataAccessInterface and TextFileTranslator. These classes are responsible for loading/saving games and the relevant methods to implement the functionality. This is a feature dependent on other classes and will therefore have a PR before Nov 14th. Harsh, Yue Fung, and Richard will review the PR.

**Comment by benxu3** [comment]
ok looks good, will you also be implementing the output and logic tree? what will those look like?
