### ISSUE TITLE
[Feature 3] Create the Menu

### ISSUE THREAD

**Issue by harshkpatel** [CSC207-2022F-UofT/course-project-the-best-monopoly-team#3]
Create the Menu Class and its features. This entails presenting a menu at the beginning of each of the players' turns and calling the game logic interactor to perform the selected action the user inputs. Another case to deal with is choosing between a saved game or a starting a new game and calling the game creating interactor and creating either a new game or loading the saved data.

**Comment by kRichard32** [comment]
Change: the menu class is now a tree that covers all possible options of the game. There are two trees, one for the initial menu and another for the game.

**Comment by harshkpatel** [comment]
The Menu is taken care of by the various treehandlers
