### ISSUE TITLE
[Feature 7] Other Half Player

### ISSUE THREAD

**Issue by harshkpatel** [CSC207-2022F-UofT/course-project-the-best-monopoly-team#7]
Create the Player Class, which represents one player, and implement the following features of the Class:
1. Attributes
2. trade()
3. changeJailStatus()
4. getPossibleActions()
5. auction() 
6. steal()

**Reviewers:**
- Cindy
- Derrick
- Susannah

**Comment by kRichard32** [comment]
We need a way to store player data and load player data.

**Comment by harshkpatel** [comment]
Same point as other half of player: needs refactoring
